### ISSUE TITLE
Only the first name is picked up when utterance containing multiple personName is given

### ISSUE THREAD

**Issue by Adityagrao** [Azure-Samples/cognitive-services-language-understanding#21]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
- Add personName as an Entity
- Use the utterance "Create a meeting with John and Ben"
- Use the utterance "Create a meeting with Ben and John"

### Any log messages given by the failure
> 
![image](https://user-images.githubusercontent.com/11465032/62136566-fd72a900-b301-11e9-9c1f-7cf2f25ffaf1.png)

![image](https://user-images.githubusercontent.com/11465032/62136609-14b19680-b302-11e9-815f-b37edb6bf545.png)

### Expected/desired behavior
> Expected both to give personName Ben and Jhon

**Comment by diberry** [comment]
Closing due to age of issue. If you feel this issue is still valid, please reopen.
