### ISSUE TITLE
Update sample to Bot Framework V4

### ISSUE THREAD

**Issue by bojingo** [Azure-Samples/cognitive-services-language-understanding#22]
Update sample of bot-integration-samples/hotel-finder to use Bot Framework V4. This repo is linked to from a primary documentation source so not appropriate to still be exclusively using an old version, especially given how much things have changed.

**Comment by diberry** [comment]
@bojingo Where is this links in documentation?

**Comment by bojingo** [comment]
Hmm... obviously I should have posted the source! Quick glance at [current documentation](https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0) references [samples](https://github.com/Microsoft/BotBuilder-Samples/blob/master/README.md) using Bot Framework V4. I'm guessing I posted this regarding a top-level link like that so thought it was an obvious problem at the time. This was posted months ago so seems has been resolved.

I'll close.
